"use client";
import "./globals.css";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
import ReactQuery from "@/lib/react-query";
import { store } from "@/store/store";
import { Provider } from "react-redux";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReactQuery>
        <Provider store={store}>
          <body>{children}</body>
        </Provider>
      </ReactQuery>
    </html>
  );
}
